### ISSUE TITLE
Wrong domains (no fix needed)

### ISSUE THREAD

**Issue by ju916** [lanmarc77/smtp_scan#1]
The extraction of emails from the PDF produces errors. We corrected some of them by hand; but some of errors escaped. Most notably those, where the (wrong) extracted address resolves via DNS.

I am aware of

- \<extracted>      -> \<should be>
- kreiscoesfeld.de         -> kreis-coesfeld.de
- rhein-neckarkreis.de -> rhein-neckar-kreis.de

I corrected those for my article manually.
This is just for documentation purposes; we will not fix this.

**Comment by lanmarc77** [comment]
I manually verified with the original PDF that there are 6 more domains affected by this problem. I am cleaning this up in fix/domainCleanUp branch and merge when ready.
This will also contain a cleaned up sqlite db/results.txt and additional scans if the domains were not scanned yet
